### ISSUE TITLE
Exception running truffle test on a fresh environment (Missing Ownable.sol)

### ISSUE THREAD

**Issue by ripper234** [daostack/daostack#39]
Steps to reproduce:

```
git clone <daostack URL>
cd daostack
truffle test
```

Error

```
Error: Could not find zeppelin/contracts/ownership/Ownable.sol from any sources; imported from /mnt/d/work/eth/daostack/contracts/SimpleVote.sol
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/index.js:76:23
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/onlyOnce.js:12:16
    at next (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/whilst.js:68:18)
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/index.js:64:7
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/fs.js:65:5
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/once.js:12:16
    at replenish (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/eachOfLimit.js:49:17)
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/onlyOnce.js:12:16
    at ReadFileContext.callback (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/fs.js:61:14)
```

Environment:
1. Windows 10 ([Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about))
2. Truffle 3.2.1

**Comment by leviadam** [comment]
I think you need to run `yarn` (equivalent to `npm install`).

**Comment by ripper234** [comment]
I now ran `yarn`. After that, `truffle test` returns

```
Error: Could not find zeppelin/contracts/lifecycle/Killable.sol from any sources; imported from /mnt/d/work/eth/daostack/contracts/controller/MintableToken.sol
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/index.js:76:23
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/onlyOnce.js:12:16
    at next (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/whilst.js:68:18)
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/index.js:64:7
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/fs.js:65:5
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/once.js:12:16
    at replenish (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/eachOfLimit.js:49:17)
    at /mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/onlyOnce.js:12:16
    at ReadFileContext.callback (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/truffle-resolver/fs.js:61:14)
```

**Comment by leviadam** [comment]
OK, Now we have progress. What happened is that zeppelin broke backwards compatibility with their package. And we did not lock the version of the zeppelin package in the package.json.
Instead of downgrading you, I pushed a version, working with the latest zeppeling.

Pull it and try `tuffle compile`.
If it works try running `testrpc` and run `truffle migrate`.

If you can compile and migrate all is OK.

**Comment by ripper234** [comment]
Output from compile:

```
truffle compile
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/SimpleVote.sol...
Compiling ./contracts/SimpleVoteInterface.sol...
Compiling ./contracts/controller/Controller.sol...
Compiling ./contracts/controller/MintableToken.sol...
Compiling ./contracts/controller/Reputation.sol...
Compiling ./contracts/debug/Debug.sol...
Compiling ./contracts/schemes/Employee.sol...
Compiling ./contracts/schemes/GenesisScheme.sol...
Compiling ./contracts/schemes/OrganizationsBoard.sol...
Compiling ./contracts/schemes/PreCoinOffering.sol...
Compiling ./contracts/schemes/SimpleContribution.sol...
Compiling ./contracts/schemes/SimpleICO.sol...
Compiling ./contracts/schemes/TokenRedemption.sol...
Compiling ./contracts/schemes/TokenSale.sol...
Compiling ./contracts/schemes/WithdrawEtherFromOldController.sol...
Compiling zeppelin/contracts/SafeMath.sol...
Compiling zeppelin/contracts/lifecycle/Destructible.sol...
Compiling zeppelin/contracts/ownership/Ownable.sol...
Compiling zeppelin/contracts/token/BasicToken.sol...
Compiling zeppelin/contracts/token/ERC20.sol...
Compiling zeppelin/contracts/token/ERC20Basic.sol...
Compiling zeppelin/contracts/token/StandardToken.sol...

/mnt/d/work/eth/daostack/contracts/controller/Reputation.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/SimpleVote.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/controller/MintableToken.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/controller/Controller.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/Employee.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/GenesisScheme.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/OrganizationsBoard.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/PreCoinOffering.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/SimpleContribution.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/SimpleICO.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/TokenRedemption.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/TokenSale.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/schemes/WithdrawEtherFromOldController.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.8+commit.60cc1668.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^
,/mnt/d/work/eth/daostack/contracts/SimpleVote.sol:16:9: Error: Undeclared identifier.
        require(msg.sender == owner);
        ^-----^
Compiliation failed. See above.
```

**Comment by leviadam** [comment]
You need to upgrade truffle.
I have pushed a corrected `package.json` that automatically installs truffle 3.2.2.

**Comment by ripper234** [comment]
Ok, managed to run tests.
Is that what you're seeing on your machine?

```
6 passing (32s)
  13 failing

  1) Contract: Proposal to distribute Tokens should respect basic sanity:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  2) Contract: Employee should respect basic sanity:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  3) Contract: Employee should not pay before startDate:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  4) Contract: Proposal to distribute Reputation should respect basic sanity:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  5) Contract: TokenSale simple scenario - buy tokens:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  6) Contract: GenesisScheme founders should get their share:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  7) Contract: GenesisScheme try to remove genesis scheme:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  8) Contract: SimpleContribution SimpleContribution scheme -> approve --> submitContribution --> submission fee:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  9) Contract: Test Token should be killable:
     TypeError: token.kill is not a function
      at Context.<anonymous> (test/token.js:21:35)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  10) Contract: MintableToken should allow minting tokens only by owner:
     AssertionError: Expected an out-of-gas error or an invalid JUMP error: expected false to be true
      at Function.assert.isTrue (/usr/lib/node_modules/truffle/node_modules/chai/lib/chai/interface/assert.js:332:31)
      at Object.module.exports.assertJumpOrOutOfGas (test/helpers.js:116:12)
      at Context.<anonymous> (test/mintabletoken.js:40:21)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  11) Contract: Test Reputation check permissions:
     AssertionError: Expected an out-of-gas error or an invalid JUMP error: expected false to be true
      at Function.assert.isTrue (/usr/lib/node_modules/truffle/node_modules/chai/lib/chai/interface/assert.js:332:31)
      at Object.module.exports.assertJumpOrOutOfGas (test/helpers.js:116:12)
      at Context.<anonymous> (test/reputation.js:32:21)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  12) Contract: Test Reputation check total reputation overflow:
     AssertionError: Invalid JUMP error must be returned: expected -1 to be above -1
      at Function.assert.isAbove (/usr/lib/node_modules/truffle/node_modules/chai/lib/chai/interface/assert.js:254:35)
      at Object.module.exports.assertJump (test/helpers.js:120:10)
      at Context.<anonymous> (test/reputation.js:83:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  13) Contract: TokenSale simple scenario - buy tokens:
     TypeError: genesis.collectFoundersShare is not a function
      at Object.setupController (test/helpers.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by leviadam** [comment]
This is indeed what you should be seeing.

**Comment by ripper234** [comment]
Great, closing this issue.
Any ETA for when the tests are expected to pass?

**Comment by leviadam** [comment]
I hope to finish with the new architecture in a week and then we can write new tests.
There is a lot of work to do.
