### ISSUE TITLE
Failing test: Contract: DAOToken log the Mint event on mint

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#91]
A test is failing in the dev branch:

```
  1) Contract: DAOToken log the Mint event on mint:

      AssertionError: expected 2 to equal 1
      at _callee6$ (C:/users/dkent/documents/projects/GitHub/DAOStack/daostack/test/daotoken.js:75:16)
      at tryCatch (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\babel-polyfill\node_modules\regenerator-runtim
e\runtime.js:117:21)
      at tryCatch (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
      at invoke (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:155:20)
      at node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:165:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by dkent600** [comment]
@leviadam  Let me know if you would like me to fix this.

**Comment by leviadam** [comment]
This is weird, if this is failing how come the travis is passing?
Have you commented it?

**Comment by dkent600** [comment]
I have no idea why it behaves differently on my machine than in Travis.  Haven't looked into it.

**Comment by stefanionescu** [comment]
Think I solved it. Will show the code soon

**Comment by leviadam** [comment]
Fixed it. Problem with new open zeppelin, adding an event.
